name = "FastBEAST"
uuid = "3fccbda2-992b-41a0-8fae-2b833e1e73d8"
authors = ["Simon B. Adrian <simon.adrian@ieee.org> and contributors"]
version = "0.1.1"

[deps]
BEAST = "bb4162c7-ba94-5a20-af32-d8ec4428bdd1"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
ExaFMMt = "add1291b-d076-47cc-8667-64576de04ee0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
BEAST = "2.4.0"
CompScienceMeshes = "0.7, 0.8"
ExaFMMt = "0.1.1"
LinearMaps = "^3"
MKL = "0.6.3, 0.7"
ParallelKMeans = "1.1"
ProgressMeter = "^1"
Random = "1"
SparseArrays = "1"
StaticArrays = "1.9"
Statistics = "1.10"
TestItemRunner = "0.2, 1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Test"]
